### ISSUE TITLE
代码太乱!!!

### ISSUE THREAD

**Issue by alex1528** [zhangqichuan/CheungSSH#40]

**Comment by nsnake** [comment]
哈哈。楼上的要求不要太苛刻了，毕竟这是针对运维的，一般来说运维做东西不需要太过于精细。

**Comment by alex1528** [comment]
我就是做运维的,真的发现代码及目录结构挺乱的,我也想着能用起来,可是挺难的啊
openstack那么多的组件,我自己就能搞起来! 为啥这个就不行!!!这说明了什么?

**Comment by alex1528** [comment]
不精细也可以,不是说简单上手不复杂的?

**Comment by alex1528** [comment]
不面对现实!!!还删帖!!!还开源放在这上面!!!
